# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dasso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ressource',
            options={'permissions': (('access_ressource', 'Access ressource'),)},
        ),
    ]
