# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 21:53
from __future__ import unicode_literals

import dasso.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasso', '0002_auto_20161119_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='manual_priority',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ressource',
            name='regex',
            #Edited to be able to remove RegexField unnecessarily complicatedspecification
            #field=dasso.fields.RegexField(default='^$'),
            field=dasso.fields.RegexCharField(default='^$', max_length=256),
        ),
    ]
