# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 21:53
from __future__ import unicode_literals

from django.db import migrations

# Generate regex fields from vhost fields
def regex_from_vhost(apps, schema_editor):
    Resource = apps.get_model("dasso", "Ressource")
    for r in Resource.objects.all():
        r.regex = r"^{}/.*$".format(r.vhost)
        print("Setting regex='{}' from vhost='{}'.".format(r.regex, r.vhost))
        r.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dasso', '0003_auto_20170102_2153'),
    ]

    operations = [
        migrations.RunPython(regex_from_vhost),
    ]
