# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dasso', '0004_auto_20170102_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressource',
            name='vhost',
        ),
    ]
