# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 15:29
from __future__ import unicode_literals

import dasso.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dasso', '0005_remove_ressource_vhost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='regex',
            field=dasso.fields.RegexCharField(default='^$', max_length=256),
        ),
    ]
