# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasso', '0006_auto_20170103_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
