# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasso', '0007_ressource_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='any_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
